### ISSUE TITLE
Release for Apple Silicon/ARM

### ISSUE THREAD

**Issue by paulsp** [MayorMonty/tm-obs-switcher#16]
This is a request to support the Apple Silicon/ARM macOS

**Comment by MayorMonty** [comment]
Apple Silicon is the platform I use for development. Currently, the triples I am producing builds for are 

```
latest-macos-x64,latest-win-x64,latest-linux-x64
```

For my usage, running the x64 layer using Rosetta 2 emulation has been sufficient for me, but your mile may vary. If you are having difficulties running on Apple Silicon, then running from the source may be an option.

**Comment by paulsp** [comment]
Please update the documentation for running on MacOS
- Add execute permission to the download file using `chmod  u+x`
- run the application.
- If you receive a `Apple can’t check app for malicious software` error, use `System Settings -> Privacy & Security` allow the application

**Comment by MayorMonty** [comment]
@paulsp I was able to hack together a version of the switcher directly integrated into Hyper, a cross-platform terminal emulator. This should be significantly more user-friendly than the previous raw executable. It is a bit more resource intensive since it runs a full Electron app as a terminal emulator.

[Releases](https://github.com/MayorMonty/tm-obs-switcher/releases/)
